
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gyuce
 */
public class MenuKullanimi extends javax.swing.JFrame {

    /**
     * Creates new form MenuKullanimi
     */
    public MenuKullanimi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        yazi_alani = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuitem_dosyaac = new javax.swing.JMenuItem();
        menuitem_dosyakaydet = new javax.swing.JMenuItem();
        menuitem_cikis = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menuitem_renkdegistir = new javax.swing.JMenuItem();
        menuitem_yazitip_arial = new javax.swing.JMenu();
        menuitem_arial = new javax.swing.JMenuItem();
        menuitem_timesnewroman = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        yazi_alani.setColumns(20);
        yazi_alani.setRows(5);
        jScrollPane1.setViewportView(yazi_alani);

        jMenu3.setText("Dosya");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        menuitem_dosyaac.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuitem_dosyaac.setText("Dosya Aç");
        menuitem_dosyaac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_dosyaacActionPerformed(evt);
            }
        });
        jMenu3.add(menuitem_dosyaac);

        menuitem_dosyakaydet.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuitem_dosyakaydet.setText("Dosya Kaydet");
        menuitem_dosyakaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_dosyakaydetActionPerformed(evt);
            }
        });
        jMenu3.add(menuitem_dosyakaydet);

        menuitem_cikis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuitem_cikis.setText("Çıkış");
        menuitem_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_cikisActionPerformed(evt);
            }
        });
        jMenu3.add(menuitem_cikis);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Düzenle");

        jMenu1.setText("Renk");

        menuitem_renkdegistir.setText("Rengi Değiştir");
        menuitem_renkdegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_renkdegistirActionPerformed(evt);
            }
        });
        jMenu1.add(menuitem_renkdegistir);

        jMenu4.add(jMenu1);

        menuitem_yazitip_arial.setText("Yazı Tipi");

        menuitem_arial.setText("Arial");
        menuitem_arial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_arialActionPerformed(evt);
            }
        });
        menuitem_yazitip_arial.add(menuitem_arial);

        menuitem_timesnewroman.setText("Times New Roman");
        menuitem_timesnewroman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_timesnewromanActionPerformed(evt);
            }
        });
        menuitem_yazitip_arial.add(menuitem_timesnewroman);

        jMenu4.add(menuitem_yazitip_arial);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuitem_dosyaacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_dosyaacActionPerformed
        JFileChooser fc = new JFileChooser();
        
        int i = fc.showOpenDialog(this);
        
        if (i == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            
            try(Scanner scanner  = new Scanner(new BufferedReader(new FileReader(file)))) {
                String content = "";
                while (scanner.hasNextLine()) {                    
                    content += scanner.nextLine() + "\n";
                }
                
                yazi_alani.setText(content);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MenuKullanimi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_menuitem_dosyaacActionPerformed

    private void menuitem_dosyakaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_dosyakaydetActionPerformed
        JFileChooser fc = new JFileChooser();
        int cevap = fc.showSaveDialog(this);
        
        if (cevap == JFileChooser.APPROVE_OPTION) {
            String dosya_yolu = fc.getSelectedFile().getPath();
            
            try(FileWriter writer = new FileWriter(dosya_yolu)) {
                writer.write(yazi_alani.getText());
                
            } catch (IOException ex) {
                Logger.getLogger(MenuKullanimi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_menuitem_dosyakaydetActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void menuitem_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_cikisActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuitem_cikisActionPerformed

    private void menuitem_renkdegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_renkdegistirActionPerformed
        Color color = JColorChooser.showDialog(this, "Bir renk seçiniz", Color.RED);
        
        yazi_alani.setForeground(color);
    }//GEN-LAST:event_menuitem_renkdegistirActionPerformed

    private void menuitem_arialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_arialActionPerformed
        Font font = new Font("Arial", Font.PLAIN, 20);
        
        yazi_alani.setFont(font);
    }//GEN-LAST:event_menuitem_arialActionPerformed

    private void menuitem_timesnewromanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_timesnewromanActionPerformed
        Font font = new Font("Times New Roman", Font.PLAIN, 20);
        
        yazi_alani.setFont(font);
    }//GEN-LAST:event_menuitem_timesnewromanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuKullanimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuKullanimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuKullanimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuKullanimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuKullanimi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuitem_arial;
    private javax.swing.JMenuItem menuitem_cikis;
    private javax.swing.JMenuItem menuitem_dosyaac;
    private javax.swing.JMenuItem menuitem_dosyakaydet;
    private javax.swing.JMenuItem menuitem_renkdegistir;
    private javax.swing.JMenuItem menuitem_timesnewroman;
    private javax.swing.JMenu menuitem_yazitip_arial;
    private javax.swing.JTextArea yazi_alani;
    // End of variables declaration//GEN-END:variables
}
